#############################################################################
# Makefile for building: STAGR.app/Contents/MacOS/STAGR
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Feb 25 01:03:49 2012
# Project:  STAGR.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile STAGR.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -lpython2.6
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -L/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -F/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = blastnSettingsDialog.cpp \
		blatSettingsDialog.cpp \
		block.cpp \
		chordDiagram.cpp \
		contigData.cpp \
		hsp.cpp \
		layerArcs.cpp \
		main.cpp \
		MultipleMatchesDialog.cpp \
		multipleMatchesView.cpp \
		pathSettingsDialog.cpp \
		plotLayer.cpp \
		scriptEditDialog.cpp \
		scriptHighlighter.cpp \
		sequenceView.cpp \
		STAGR.cpp \
		Table.cpp moc_blastnSettingsDialog.cpp \
		moc_blatSettingsDialog.cpp \
		moc_chordDiagram.cpp \
		moc_MultipleMatchesDialog.cpp \
		moc_multipleMatchesView.cpp \
		moc_pathSettingsDialog.cpp \
		moc_scriptEditDialog.cpp \
		moc_scriptHighlighter.cpp \
		moc_sequenceView.cpp \
		moc_STAGR.cpp \
		moc_Table.cpp \
		qrc_STAGR.cpp
OBJECTS       = blastnSettingsDialog.o \
		blatSettingsDialog.o \
		block.o \
		chordDiagram.o \
		contigData.o \
		hsp.o \
		layerArcs.o \
		main.o \
		MultipleMatchesDialog.o \
		multipleMatchesView.o \
		pathSettingsDialog.o \
		plotLayer.o \
		scriptEditDialog.o \
		scriptHighlighter.o \
		sequenceView.o \
		STAGR.o \
		Table.o \
		moc_blastnSettingsDialog.o \
		moc_blatSettingsDialog.o \
		moc_chordDiagram.o \
		moc_MultipleMatchesDialog.o \
		moc_multipleMatchesView.o \
		moc_pathSettingsDialog.o \
		moc_scriptEditDialog.o \
		moc_scriptHighlighter.o \
		moc_sequenceView.o \
		moc_STAGR.o \
		moc_Table.o \
		qrc_STAGR.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		STAGR.pro
QMAKE_TARGET  = STAGR
DESTDIR       = 
TARGET        = STAGR.app/Contents/MacOS/STAGR

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile STAGR.app/Contents/PkgInfo STAGR.app/Contents/Resources/empty.lproj STAGR.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) STAGR.app/Contents/MacOS/ || $(MKDIR) STAGR.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: STAGR.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile STAGR.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile STAGR.pro

STAGR.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) STAGR.app/Contents || $(MKDIR) STAGR.app/Contents 
	@$(DEL_FILE) STAGR.app/Contents/PkgInfo
	@echo "APPL????" >STAGR.app/Contents/PkgInfo
STAGR.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) STAGR.app/Contents/Resources || $(MKDIR) STAGR.app/Contents/Resources 
	@touch STAGR.app/Contents/Resources/empty.lproj
	
STAGR.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) STAGR.app/Contents || $(MKDIR) STAGR.app/Contents 
	@$(DEL_FILE) STAGR.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,STAGR,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >STAGR.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/STAGR1.0.0 || $(MKDIR) .tmp/STAGR1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/STAGR1.0.0/ && $(COPY_FILE) --parents blastnSettingsDialog.h blatSettingsDialog.h block.h chordDiagram.h contigData.h hsp.h layerArcs.h MultipleMatchesDialog.h multipleMatchesView.h pathSettingsDialog.h plotLayer.h scriptEditDialog.h scriptHighlighter.h sequenceView.h STAGR.h Table.h .tmp/STAGR1.0.0/ && $(COPY_FILE) --parents STAGR.qrc .tmp/STAGR1.0.0/ && $(COPY_FILE) --parents blastnSettingsDialog.cpp blatSettingsDialog.cpp block.cpp chordDiagram.cpp contigData.cpp hsp.cpp layerArcs.cpp main.cpp MultipleMatchesDialog.cpp multipleMatchesView.cpp pathSettingsDialog.cpp plotLayer.cpp scriptEditDialog.cpp scriptHighlighter.cpp sequenceView.cpp STAGR.cpp Table.cpp .tmp/STAGR1.0.0/ && (cd `dirname .tmp/STAGR1.0.0` && $(TAR) STAGR1.0.0.tar STAGR1.0.0 && $(COMPRESS) STAGR1.0.0.tar) && $(MOVE) `dirname .tmp/STAGR1.0.0`/STAGR1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/STAGR1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r STAGR.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_blastnSettingsDialog.cpp moc_blatSettingsDialog.cpp moc_chordDiagram.cpp moc_MultipleMatchesDialog.cpp moc_multipleMatchesView.cpp moc_pathSettingsDialog.cpp moc_scriptEditDialog.cpp moc_scriptHighlighter.cpp moc_sequenceView.cpp moc_STAGR.cpp moc_Table.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_blastnSettingsDialog.cpp moc_blatSettingsDialog.cpp moc_chordDiagram.cpp moc_MultipleMatchesDialog.cpp moc_multipleMatchesView.cpp moc_pathSettingsDialog.cpp moc_scriptEditDialog.cpp moc_scriptHighlighter.cpp moc_sequenceView.cpp moc_STAGR.cpp moc_Table.cpp
moc_blastnSettingsDialog.cpp: blastnSettingsDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ blastnSettingsDialog.h -o moc_blastnSettingsDialog.cpp

moc_blatSettingsDialog.cpp: blatSettingsDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ blatSettingsDialog.h -o moc_blatSettingsDialog.cpp

moc_chordDiagram.cpp: plotLayer.h \
		contigData.h \
		layerArcs.h \
		chordDiagram.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ chordDiagram.h -o moc_chordDiagram.cpp

moc_MultipleMatchesDialog.cpp: Table.h \
		hsp.h \
		sequenceView.h \
		block.h \
		multipleMatchesView.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		MultipleMatchesDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MultipleMatchesDialog.h -o moc_MultipleMatchesDialog.cpp

moc_multipleMatchesView.cpp: hsp.h \
		multipleMatchesView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ multipleMatchesView.h -o moc_multipleMatchesView.cpp

moc_pathSettingsDialog.cpp: pathSettingsDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ pathSettingsDialog.h -o moc_pathSettingsDialog.cpp

moc_scriptEditDialog.cpp: scriptHighlighter.h \
		scriptEditDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ scriptEditDialog.h -o moc_scriptEditDialog.cpp

moc_scriptHighlighter.cpp: scriptHighlighter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ scriptHighlighter.h -o moc_scriptHighlighter.cpp

moc_sequenceView.cpp: block.h \
		hsp.h \
		sequenceView.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sequenceView.h -o moc_sequenceView.cpp

moc_STAGR.cpp: MultipleMatchesDialog.h \
		Table.h \
		hsp.h \
		sequenceView.h \
		block.h \
		multipleMatchesView.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		blastnSettingsDialog.h \
		blatSettingsDialog.h \
		scriptEditDialog.h \
		scriptHighlighter.h \
		pathSettingsDialog.h \
		STAGR.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ STAGR.h -o moc_STAGR.cpp

moc_Table.cpp: hsp.h \
		Table.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Table.h -o moc_Table.cpp

compiler_rcc_make_all: qrc_STAGR.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_STAGR.cpp
qrc_STAGR.cpp: STAGR.qrc \
		script.py \
		MAC.fasta \
		MIC.fasta \
		output2dict.py \
		icons/loadSequencesIcon.png \
		icons/pythonIcon.png \
		icons/stagrSettingsIcon.png \
		icons/settingsIcon.png \
		icons/startIcon.png
	/Developer/Tools/Qt/rcc -name STAGR STAGR.qrc -o qrc_STAGR.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

blastnSettingsDialog.o: blastnSettingsDialog.cpp blastnSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blastnSettingsDialog.o blastnSettingsDialog.cpp

blatSettingsDialog.o: blatSettingsDialog.cpp blatSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blatSettingsDialog.o blatSettingsDialog.cpp

block.o: block.cpp block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o block.cpp

chordDiagram.o: chordDiagram.cpp chordDiagram.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		hsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chordDiagram.o chordDiagram.cpp

contigData.o: contigData.cpp contigData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contigData.o contigData.cpp

hsp.o: hsp.cpp hsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hsp.o hsp.cpp

layerArcs.o: layerArcs.cpp layerArcs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layerArcs.o layerArcs.cpp

main.o: main.cpp STAGR.h \
		MultipleMatchesDialog.h \
		Table.h \
		hsp.h \
		sequenceView.h \
		block.h \
		multipleMatchesView.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		blastnSettingsDialog.h \
		blatSettingsDialog.h \
		scriptEditDialog.h \
		scriptHighlighter.h \
		pathSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MultipleMatchesDialog.o: MultipleMatchesDialog.cpp MultipleMatchesDialog.h \
		Table.h \
		hsp.h \
		sequenceView.h \
		block.h \
		multipleMatchesView.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		chordDiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultipleMatchesDialog.o MultipleMatchesDialog.cpp

multipleMatchesView.o: multipleMatchesView.cpp multipleMatchesView.h \
		hsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multipleMatchesView.o multipleMatchesView.cpp

pathSettingsDialog.o: pathSettingsDialog.cpp pathSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pathSettingsDialog.o pathSettingsDialog.cpp

plotLayer.o: plotLayer.cpp plotLayer.h \
		contigData.h \
		layerArcs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotLayer.o plotLayer.cpp

scriptEditDialog.o: scriptEditDialog.cpp scriptHighlighter.h \
		scriptEditDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scriptEditDialog.o scriptEditDialog.cpp

scriptHighlighter.o: scriptHighlighter.cpp scriptHighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scriptHighlighter.o scriptHighlighter.cpp

sequenceView.o: sequenceView.cpp sequenceView.h \
		block.h \
		hsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequenceView.o sequenceView.cpp

STAGR.o: STAGR.cpp STAGR.h \
		MultipleMatchesDialog.h \
		Table.h \
		hsp.h \
		sequenceView.h \
		block.h \
		multipleMatchesView.h \
		plotLayer.h \
		contigData.h \
		layerArcs.h \
		blastnSettingsDialog.h \
		blatSettingsDialog.h \
		scriptEditDialog.h \
		scriptHighlighter.h \
		pathSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STAGR.o STAGR.cpp

Table.o: Table.cpp Table.h \
		hsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Table.o Table.cpp

moc_blastnSettingsDialog.o: moc_blastnSettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blastnSettingsDialog.o moc_blastnSettingsDialog.cpp

moc_blatSettingsDialog.o: moc_blatSettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blatSettingsDialog.o moc_blatSettingsDialog.cpp

moc_chordDiagram.o: moc_chordDiagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chordDiagram.o moc_chordDiagram.cpp

moc_MultipleMatchesDialog.o: moc_MultipleMatchesDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MultipleMatchesDialog.o moc_MultipleMatchesDialog.cpp

moc_multipleMatchesView.o: moc_multipleMatchesView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multipleMatchesView.o moc_multipleMatchesView.cpp

moc_pathSettingsDialog.o: moc_pathSettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pathSettingsDialog.o moc_pathSettingsDialog.cpp

moc_scriptEditDialog.o: moc_scriptEditDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scriptEditDialog.o moc_scriptEditDialog.cpp

moc_scriptHighlighter.o: moc_scriptHighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scriptHighlighter.o moc_scriptHighlighter.cpp

moc_sequenceView.o: moc_sequenceView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sequenceView.o moc_sequenceView.cpp

moc_STAGR.o: moc_STAGR.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_STAGR.o moc_STAGR.cpp

moc_Table.o: moc_Table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Table.o moc_Table.cpp

qrc_STAGR.o: qrc_STAGR.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_STAGR.o qrc_STAGR.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

